"""Render docs/MODEL_CARD.md from model_metadata.json (so the card can't drift from the artefact).

python -m ml.model_card artifacts/model/model_metadata.json > docs/MODEL_CARD.md
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def _ms(summary: dict, key: str) -> str:
    return f"{summary[key]['mean']:.3f} ± {summary[key]['std']:.3f}"


def render(meta: dict) -> str:
    ev = meta["evaluation"]
    test = ev["test"]
    m = test["metrics"]
    perm = ev.get("permutation_test")
    lines = [
        f"# Model card — `{meta['model_name']}`",
        "",
        "> Generated by `python -m ml.model_card` from `artifacts/model/model_metadata.json`. Do not edit by hand.",
        "",
        "| | |",
        "|---|---|",
        f"| Version | `{meta['model_version']}` (trained {meta['trained_at']}) |",
        "| Task | At booking time, predict whether a shipment will arrive **more than 24 h late** |",
        f"| Target | `{meta['target']}`, positive rate {meta['data']['positive_rate']:.1%} |",
        f"| Training data | {meta['data']['labelled_rows']:,} labelled shipments, bookings "
        f"{meta['data']['booking_date_min'][:10]} → {meta['data']['booking_date_max'][:10]} |",
        f"| Split | {meta['split']['method']} |",
        f"| Selected model | `{meta['selection']['chosen']}` — {meta['selection']['rationale']} |",
        f"| Decision threshold | {meta['decision_threshold']} (class-balanced model) |",
        f"| Artefact | `delay_model.joblib`, sha256 `{meta['artifact_sha256'][:16]}…`, scikit-learn "
        f"{meta['sklearn_version']} |",
        "",
        "## Features (all known at booking time)",
        "",
        "| Feature | Why it is included |",
        "|---|---|",
    ]
    lines += [f"| `{k}` | {v} |" for k, v in meta["feature_docs"].items()]
    lines += ["", "**Deliberately excluded**", "", "| Field | Reason |", "|---|---|"]
    lines += [f"| `{k}` | {v} |" for k, v in meta["excluded_features"].items()]
    lines += [
        "",
        "## Model selection — rolling-origin cross-validation on the development set",
        "",
        "| Candidate | Servable | ROC-AUC | PR-AUC | F1 | Brier |",
        "|---|---|---|---|---|---|",
    ]
    for name, exp in meta["experiments"].items():
        s = exp["summary"]
        lines.append(
            f"| `{name}` | {'yes' if exp['servable'] else 'no (needs feature store)'} | "
            f"{_ms(s, 'roc_auc')} | {_ms(s, 'pr_auc')} | {_ms(s, 'f1')} | {_ms(s, 'brier')} |"
        )
    lines += [
        "",
        f"## Final evaluation — untouched test set ({m['n']} shipments, bookings from "
        f"{meta['split']['test_booking_date_from'][:10]})",
        "",
        "| Metric | Model | Always predict late | Prior (base rate) |",
        "|---|---|---|---|",
    ]
    b1, b2 = test["baselines"]["always_predict_delayed"], test["baselines"]["prior_base_rate"]
    for key in ("precision", "recall", "f1", "roc_auc", "pr_auc", "brier"):
        lines.append(f"| {key} | **{m[key]}** | {b1[key]} | {b2[key]} |")
    ci, pci = test["roc_auc_ci"], test["pr_auc_ci"]
    lines += [
        "",
        f"95% bootstrap CI — ROC-AUC **{ci['point']} [{ci['ci_low']}, {ci['ci_high']}]**, "
        f"PR-AUC {pci['point']} [{pci['ci_low']}, {pci['ci_high']}] (base rate {m['positive_rate_true']}).",
        "",
    ]
    if perm:
        lines += [
            "### Label-permutation sanity test",
            "",
            f"The same CV was repeated {perm['n_permutations']} times with **shuffled labels**. Null-model AUC: "
            f"mean {perm['null_auc_mean']}, 95th percentile {perm['null_auc_p95']}. Real model: "
            f"{perm['observed_cv_auc']} → **p = {perm['p_value']}**.",
            "",
        ]
    lines += [
        "### Threshold trade-off (test set)",
        "",
        "| Threshold | Precision | Recall | F1 | Flagged |",
        "|---|---|---|---|---|",
    ]
    lines += [
        f"| {r['threshold']} | {r['precision']} | {r['recall']} | {r['f1']} | {r['flagged_rate']:.0%} |"
        for r in test["threshold_table"]
    ]
    lines += [
        "",
        "### Calibration (test set)",
        "",
        "| Predicted bin | n | Mean predicted | Observed late rate |",
        "|---|---|---|---|",
    ]
    lines += [f"| {c['bin']} | {c['n']} | {c['mean_predicted']} | {c['observed_rate']} |" for c in test["calibration"]]
    lines += [
        "",
        "## Interpretation and intended use",
        "",
        "- **The model has no detectable predictive signal on this dataset.** Test ROC-AUC's confidence interval "
        "contains 0.5 and the permutation test cannot distinguish it from models trained on random labels. Every "
        "candidate — including gradient boosting and leakage-safe history features — lands in the same place.",
        "- Profiling agrees: no booking-time field moves the late rate by more than a few points (see "
        "`docs/DATA_QUALITY.md` → `planned_transit_outlier_for_route`; same-lane transit times vary 3–35 days).",
        "- Probabilities are **not calibrated** (class-balanced training centres them on 0.5). Use the risk band "
        "as a *relative* signal at most; do not use the probability as a true likelihood.",
        "- **Not suitable for automated decisions.** It is shipped to prove the serving, monitoring and leakage "
        "boundaries end-to-end; the same pipeline will pick up signal as soon as better features exist.",
        "",
        "## Monitoring",
        "",
        "`python -m ml.monitor --from <date>` compares a window of bookings against the training reference stored "
        "in the metadata (PSI per feature and on predictions), measures live performance on shipments whose "
        "outcome is known, and prints a retrain decision. Triggers are documented in the README.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    path = Path(args[0] if args else "artifacts/model/model_metadata.json")
    print(render(json.loads(path.read_text(encoding="utf-8"))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
