"""Render the JSON DQ report as Markdown documentation.

    python -m dq.render artifacts/dq_report.json > docs/DATA_QUALITY.md

Generated from the report itself, so the docs can never drift from what the checks actually found.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_DATASETS = ("shipments", "ports", "port_events")
_SEVERITY_ORDER = {"critical": 0, "warning": 1, "info": 2}


def _cell(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def render(report: dict) -> str:
    s = report["summary"]
    files = report.get("input_files", {})
    lines = [
        "# Data quality report",
        "",
        "> Generated by `python -m dq.render` from the output of `python -m dq` — do not edit by hand.",
        "",
        f"Generated at **{report.get('generated_at')}** against:",
        "",
        "| Dataset | File | Rows | SHA-256 |",
        "|---|---|---:|---|",
    ]
    lines += [f"| {k} | `{v['file']}` | {v['rows']:,} | `{v['sha256'][:12]}…` |" for k, v in files.items()]
    lines += [
        "",
        f"**{s['checks_run']} checks** — {s['checks_passed']} passed, {s['checks_failed']} found issues, "
        f"{s['checks_errored']} errored. Failing by severity: "
        + ", ".join(
            f"{k} {v}" for k, v in sorted(s["failed_by_severity"].items(), key=lambda kv: _SEVERITY_ORDER[kv[0]])
        )
        + ".",
        "",
        "Severity: **critical** = would corrupt metrics or the model if left in · **warning** = degrades quality, "
        "fixed or flagged in curation · **info** = worth knowing, no change made.",
        "",
    ]
    for ds in _DATASETS:
        failing = sorted(
            (c for c in report["checks"] if c["dataset"] == ds and c["status"] != "pass"),
            key=lambda c: (_SEVERITY_ORDER[c["severity"]], -c["rows_affected"]),
        )
        passing = [c for c in report["checks"] if c["dataset"] == ds and c["status"] == "pass"]
        lines += [f"## `{ds}`", ""]
        if failing:
            lines += [
                "| Check | Severity | Rows (%) | How detected | Decision | Reasoning |",
                "|---|---|---:|---|---|---|",
            ]
            lines += [
                f"| `{c['check_name'].split('.', 1)[1]}`<br>{_cell(c['description'])} | {c['severity']} | "
                f"{c['rows_affected']:,} ({c['pct_affected']}%) | {_cell(c.get('detection', ''))} | "
                f"**{c['action']}** | {_cell(c['rationale'])} |"
                for c in failing
            ]
        if passing:
            names = ", ".join(f"`{c['check_name'].split('.', 1)[1]}`" for c in passing)
            lines += ["", f"Passing (kept as regression guards): {names}."]
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    path = Path(args[0] if args else "artifacts/dq_report.json")
    print(render(json.loads(path.read_text(encoding="utf-8"))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
